### ISSUE TITLE
What do the digits in the "Activity" page mean?

### ISSUE THREAD

**Issue by huskier** [lsk569937453/git-statistic#17]
There are many digits in the "Activity" page. What do those digits mean?

**Comment by lsk569937453** [comment]
The "Activity" tab displays commit statistics at various levels:

* 32-week view: Shows the commit count for each of the past 32 weeks.
* Hourly statistics: Shows the commit count for each hour of the day.
* Weekly statistics: Shows the commit count for each day of the week.
* Monthly statistics: Shows the commit count for each month of the year.
* Yearly statistics: Shows the total commit count for the entire year.

**Comment by huskier** [comment]
OK, it's all about commit count. Thanks.
